### PR TITLE
RpcCaller._setup_link - set mapped file size manually

### PR DESCRIPTION
**Pull request by SilverIce**
Otherwise crashes under linux. Feel free to skip it - not sure whether there is point to run the application under this OS

### CODE REVIEW

**Comment by TheTerrasque** [comment]
Hmm.. Been musing about this a bit. 

In the end, I don't see how it will work on Linux without making a full MO Linux port. And in the spirit of keeping things simple and not adding "unneeded" code to what already works, I'll keep this out for now.

**Comment by SilverIce** [comment]
There is a way to run MO via WINE (Haven't found issues running Oblivion, too). Though, with WINE `mmap.mmap` shouldn't crash

**Comment by TheTerrasque** [comment]
Does MO run under wine? With the file system layer and everything? mmap.mmap probably wouldn't crash, but I think the file path would be different.

**Comment by SilverIce** [comment]
I just played the game (via MO), didn't tested much. There is filesystem layer. But I was testing the app. directly under Linux (and in this case it creates the file somewhere in /tmp). Din't tested it in conjuction with MO + wine

**Pull request merged**
